version: "3"
services:
  api:
    # build: .
    image: ahorasan/fastapi
    depends_on:
      - postgres
    ports: [80:8000]
    # Bind Mount'u kaldırıyoruz...
    # volumes:
    #   - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # Buradan --reload çıkarıldı. Çünkü Production ortamında gerek yok.
    # Veya comment'leyebiliriz.
    # env_file:
    #   - ./env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
